### ISSUE TITLE
README file lacks information about how to use the project

### ISSUE THREAD

**Issue by fedyiv** [decentralized-identity/keripy#49]
Hello,

I have watched SSI Meetup https://ssimeetup.org/key-event-receipt-infrastructure-keri-secure-identifier-overlay-internet-sam-smith-webinar-58/ and checked corresponding whitepaper, but despite of that it is not clear what this particular project does.

It seems like README only has installation instructions for dependency libraries.

What I would like to understand from README is how  this source code can be used, what logic is covered related to the whitepaper and how to deploy a network based on this code.

Is it possible to provide such information?

**Comment by SmithSamuelM** [comment]
It’s still in early development.  It’s not yet in a usable state

**Comment by shoyebinamdar** [comment]
@SmithSamuelM I have same query. I am able to setup the keripy on my local system, all tests passing. But now I don't know how to use it.
